import { CartCounter } from '@/shopping-cart/components';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Counter',
	description: 'Generated by create next app',
};

const CounterPage = () => {
	return (
		<div className='flex flex-col justify-center items-center h-screen w-full'>
			<span className=''>Cart</span>
			<CartCounter value={20} />
		</div>
	);
};

export default CounterPage;
