import { SimpleWidget } from '@/components';
import WidgetsGrid from '@/components/dashboard/WidgetsGrid';
import { Metadata } from 'next';
export const metadata: Metadata = {
	title: 'Dashboard',
	description: 'Generated by create next app',
};
const DashboardMain = () => {
	return (
		<div className='text-black'>
			<h1 className='mt-2 text-3xl'>Dashboard</h1>
			<span className='text-xl'>General Information</span>
			<WidgetsGrid value={20} />
			{/* <div className='flex flex-wrap justify-center items-center gap-3'>
				<SimpleWidget />
			</div> */}
		</div>
	);
};

export default DashboardMain;
